cyber_keywords = [
    "cybersecurity",
    "who is you",
    "hi",
    "hello",
    "hey",
    "howdy",
    "hi there",
    "hey there",
    "good morning",
    "good afternoon",
    "good evening",
    "greetings",
    "what's up",
    "sup",
    "yo",
    "hi bot",
    "hello bot",
    "hey chatbot",
    "hey assistant",
    "good to see you",
    "nice to meet you",
    "how are you",
    "how's it going",
    "how have you been",
    "long time no see",
    "what's new",
    "any updates",
    "what can you do",
    "tell me about yourself",
    "who are you",
    "cyber attacks",
    "cyber", 
    "threat warning", 
    "security breach"
    "access control",
    "adware",
    "advanced persistent threat",
    "anonymity",
    "anti-malware",
    "application security",
    "authentication",
    "authorization",
    "backdoor",
    "biometrics",
    "botnet",
    "brute force",
    "business continuity",
    "cloud security",
    "computer forensics",
    "confidentiality",
    "cyber defense",
    "cyber insurance",
    "cyber threat intelligence",
    "cybercrime",
    "cybersecurity framework",
    "data encryption",
    "data loss prevention",
    "data privacy",
    "data protection",
    "data security",
    "denial of service",
    "digital certificate",
    "digital forensics",
    "distributed denial of service",
    "downtime",
    "drive-by download",
    "endpoint protection",
    "encryption",
    "exploit",
    "firewall",
    "fraud detection",
    "hacker",
    "hacking",
    "identity theft",
    "incident response",
    "industrial control system",
    "information security",
    "insider threat",
    "internet of things",
    "intrusion detection",
    "keylogger",
    "malicious code",
    "malware",
    "man-in-the-middle attack",
    "mobile security",
    "multi-factor authentication",
    "network security",
    "open source security",
    "password security",
    "patch management",
    "penetration testing",
    "phishing",
    "ransomware",
    "risk assessment",
    "rootkit",
    "security audit",
    "security awareness",
    "security breach",
    "security policy",
    "security vulnerability",
    "server security",
    "session hijacking",
    "social engineering",
    "spam",
    "spyware",
    "system security",
    "tunneling",
    "two-factor authentication",
    "user awareness",
    "virus",
    "virtual private network",
    "vulnerability assessment",
    "web application security",
    "wireless security",
    "zero-day exploit",
    "access management",
    "antivirus",
    "asset protection",
    "audit trail",
    "behavioral analytics",
    "big data security",
    "business impact analysis",
    "certification",
    "cloud computing",
    "compliance",
    "container security",
    "cybersecurity governance",
    "cybersecurity operations",
    "cybersecurity risk",
    "data breach",
    "data center security",
    "data classification",
    "data leakage",
    "data integrity",
    "data retention",
    "database security",
    "digital signature",
    "email security",
    "endpoint security",
    "exploit kit",
    "file integrity monitoring",
    "forensic analysis",
    "governance risk and compliance",
    "hashing",
    "honeypot",
    "incident management",
    "information assurance",
    "information governance",
    "internet security",
    "intrusion prevention system",
    "key management",
    "log analysis",
    "machine learning security",
    "mobile device management",
    "network monitoring",
    "operational security",
    "policies and procedures",
    "privacy impact assessment",
    "public key infrastructure",
    "recovery point objective",
    "recovery time objective",
    "red teaming",
    "DoS",
    "risk management",
    "secure coding",
    "security architecture",
    "security assessment",
    "security control",
    "security engineering",
    "security incident",
    "security metrics",
    "security operations center",
    "security patch",
    "security posture",
    "security program",
    "security scanning",
    "security training",
    "social media security",
    "software security",
    "supply chain security",
    "system integrity",
    "threat hunting",
    "virtualization security",
    "web security",
    "zero trust",
    "drp",
    "ldap",
    "dnssec",
    "waf",
    "soc2",
    "jwt",
    "dns",
    "ddos",
    "pci dss",
    "cia",
    "nac",
    "byod",
    "socaas",
    "ip",
    "ips",
    "rsa",
    "rdp",
    "fw",
    "xss",
    "ueba",
    "soc",
    "iocs",
    "api",
    "rat",
    "mitm",
    "wpa",
    "dkim",
    "siem",
    "iot",
    "hids",
    "apt",
    "iam",
    "fde",
    "iso",
    "vpn",
    "sqli",
    "sso",
    "csp",
    "smb",
    "rce",
    "owasp",
    "https",
    "pam",
    "iamaas",
    "http",
    "soar",
    "aes",
    "dast",
    "hipaa",
    "url",
    "rbac",
    "fips",
    "cti",
    "ids",
    "cve",
    "tls",
    "pki",
    "vapt",
    "saas",
    "ssl",
    "dlp",
    "ctf",
    "osint",
    "ipsec",
    "bcp",
    "ssrf",
    "spf",
    "mfa",
    "dmarc",
    "ir",
    "apt29",
    "nist",
    "edr",
    "csrf",
    "nids",
    "mitre",
    "sast",
    "gdpr",
    "pii",
    "mac",
    "ssh",
    "dos"
]

